apiVersion: v1
kind: Pod
metadata:
  name: my-first-pod # 他と被り禁止
  labels:
    component: nginx
spec:
  containers:
    # docker runに渡す情報
    - name: nginx # pod内で区別するためのcontainer-name
      image: nginx:latest
      resources:
        requests:
          cpu: "100m"
          memory: "128Mi"
        limits:
          cpu: "500m"
          memory: "256Mi"
