apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  labels:
    component: nginx

spec:
  replicas: 3
  selector:
    matchLabels:
      component: nginx
  template:
    metadata:
      labels:
        component: nginx
    spec:
      containers:
      - name: nginx
        # image: nginx:1.20
        image: nginx:1.30
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
