apiVersion: apps/v1
kind: Deployment

metadata:
  name: nginx-deployment
  namespace: nginx-namespace
# Deploymentの仕様
spec:
  replicas: 2 # 最低２つは維持する

  selector:
    matchLabels:
      app: nginx-pod-label

  template:
    metadata:
      labels:
        app: nginx-pod-label
    # Podの仕様
    spec:
      containers:
        - name: web-nginx-container

          image: nginx:1.27.2-alpine
          imagePullPolicy: IfNotPresent

          ports:
            - name: web-port
              containerPort: 80

          resources:
            requests:
              cpu: 100m # 100m = 0.1 CPU
              memory: 128Mi

            limits:
              cpu: 200m
              memory: 256Mi
          # health check
          livenessProbe:
            httpGet:
              path: /
              port: web-port # ports設定の名前
            initialDelaySeconds: 5
            periodSeconds: 10
          #receive request check
          readinessProbe:
            httpGet:
              path: /
              port: web-port
            initialDelaySeconds: 5
            periodSeconds: 10
