FROM mcr.microsoft.com/devcontainers/base:2-debian12 AS toolchain

ENV DEBIAN_FRONTEND="noninteractive"
RUN apt-get -qq update && \
    apt-get -qq -y install --no-install-recommends \
    ca-certificates

WORKDIR /tmp
ARG BIN=/usr/local/bin
ARG COMPD=/etc/bash_completion.d/

ARG KUBECTL_VERSION=v1.31.0
ARG KUBECTL_URL=https://dl.k8s.io/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl
RUN curl -fsSL "${KUBECTL_URL}" -o kubectl && \
    install -m 755 kubectl ${BIN}/kubectl && \
    kubectl completion bash > ${COMPD}/kubectl

ARG MINIKUBE_VERSION=v1.36.0
ARG MINIKUBE_URL=https://storage.googleapis.com/minikube/releases/${MINIKUBE_VERSION}/minikube-linux-amd64
RUN curl -fsSL "${MINIKUBE_URL}" -o minikube && \
    install -m 755 minikube ${BIN}/minikube && \
    minikube completion bash > ${COMPD}/minikube

ARG HELM_VERSION=v4.0.0
ARG HELM_URL=https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz
RUN curl -fsSL "${HELM_URL}" -o helm.tar.gz && \
    tar -xzf helm.tar.gz && \
    install -m 755 linux-amd64/helm ${BIN}/helm && \
    helm completion bash > ${COMPD}/helm

ARG HELMFILE_VERSION=1.7.4
ARG HELMFILE_URL=https://github.com/helmfile/helmfile/releases/download/v${HELMFILE_VERSION}/helmfile_${HELMFILE_VERSION}_linux_amd64.tar.gz
RUN curl -fsSL "${HELMFILE_URL}" -o helmfile.tar.gz && \
    mkdir -p linux-amd64 && tar -xzf helmfile.tar.gz -C linux-amd64 && \
    install -m 755 linux-amd64/helmfile ${BIN}/helmfile && \
    helmfile completion bash > ${COMPD}/helmfile

ARG AWSCLI_VERSION=2.28.23
ARG AWSCLI_URL=https://awscli.amazonaws.com/awscli-exe-linux-x86_64-${AWSCLI_VERSION}.zip
RUN curl -fsSL "${AWSCLI_URL}" -o awscliv2.zip && \
    unzip -q awscliv2.zip && \
    ./aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli && \
    aws_completer > /etc/bash_completion.d/aws

# hadolint
ARG HADOLINT_URL="https://github.com/hadolint/hadolint/releases/download/v2.12.0/hadolint-Linux-x86_64"
RUN curl -fsSL "${HADOLINT_URL}" -o hadolint && \
    install -m 755 hadolint /usr/local/bin/hadolint
# diff-highlighta
WORKDIR /usr/share/doc/git/contrib/diff-highlight
RUN make

FROM mcr.microsoft.com/devcontainers/base:2-debian12

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get -qq update\
    && apt-get -y install --no-install-recommends \
    # utilities
    peco\
    ripgrep\
    silversearcher-ag\
    vim\
    # network tools
    telnet\
    netcat-openbsd\
    && apt-get clean\
    && rm -rf /var/lib/apt/lists/*

# tools
# /usr/local/bin/awsは/usr/local/aws-cli/v2/current/bin/aws*へのシンボリックリンクである。
# COPY --from=toolchain /usr/local/bin/aws /usr/local/bin/awsはシンボリックリンク先まで追ってコピーする挙動を取る。
# そのため、マルチステージコンテナからコピーしたければ、/usr/local/bin全体をコピーするしかない。
COPY --from=toolchain /usr/local/bin /usr/local/bin
COPY --from=toolchain /usr/local/aws-cli /usr/local/aws-cli
COPY --from=toolchain /etc/bash_completion.d /etc/bash_completion.d
COPY --from=toolchain /usr/share/doc/git/contrib/diff-highlight/diff-highlight /usr/local/bin/diff-highlight
